### ISSUE TITLE
distutils will disappear with Python 3.12: mesonpy ?

### ISSUE THREAD

**Issue by picca** [hyperspy/rosettasciio#152]
While preparing the Debian package of hyperspy I have warning about the deprecated distutils modules.

mesonpy seems to the the best candidate to  build and distribute Python extension. numpy, scipy, pyfai, python-fabio have already migrated to this build system.

Could you considere  using this build system to allow a better support  in our distributions.

thanks considering

Frédéric

**Comment by ericpre** [comment]
I have transferred the issue here, as the cython code of the bcf reader now lives here.

I am not sure `distutils` is needed anymore, as this is only used to check if a c-compiler is working and provide a nicer error message:
https://github.com/hyperspy/rosettasciio/blob/7f1612955640031a5634e51b3bc0a87b3e9a1dc7/setup.py#L92C1-L106
